name: 'Preview environment controller labels cleanup'
description: 'Remove deploy PR labels'
author: hello@cloudposse.com
branding:
  icon: 'delete'
  color: 'white'
inputs:
  labels_env:
    description: "JSON formatted {label}: {environment} map "
    required: true
    default: "{}"
  env:
    description: Environment
    required: true
  pr_number:
    description: The number of the pull request, which will default to extracting from the workflow event if not specified.
    required: false
outputs: {}
runs:
  using: "composite"
  steps:
    - uses: cloudposse/github-action-jq@0.4.0
      id: label
      with:
        compact: true
        raw-output: true
        input: ${{ inputs.labels_env }}
        script: ${{ format('.{0}', inputs.env) }}

    - uses: peter-murray/remove-labels-action@v1
      with:
        labels: ${{ steps.label.outputs.output }}
        issue_number: ${{ inputs.pr_number }}
